services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "${POSTGRES_PORT_EXT}:${POSTGRES_PORT}"
    volumes:
      - members-data-tu:/var/lib/postgresql/data
    restart: always


  backend:
    container_name: backend
    depends_on:
      - postgres
    image: members/backend
    env_file:
      - .env
    ports: 
      - "${BACKEND_PORT_EXT}:8002"
    volumes:
      - ./backend/mitgliederverwaltung:/usr/src/app
    restart: always


  nginx:
    container_name: nginx
    image: members/nginx
    ports:
      - "${NGINX_PORT_EXT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/build:/usr/share/nginx/html:ro
    restart: always
